const projects = [
  {
    id: 1,
    slug: 'c-study',
    title: 'Collaborative Study Platform',
    year: '2026',
    tech: ['React', 'Node.js', 'Express', 'Socket.io', 'MongoDB', 'Gemini AI', 'Tailwind CSS'],
    description:
      'A real-time collaborative study platform featuring interactive classrooms, document rendering, and AI-powered study tools. Students can join virtual study rooms to collaborate on files, utilize text-to-speech learning aids, and query an AI assistant for summaries. Teachers can upload resource materials and participate in peer-to-peer discussions.',
    myRole: [
      'Designed and implemented real-time classroom state synchronization and live chat using Express and Socket.io.',
      'Integrated Google Gemini and Groq AI SDKs to build an automated AI Study Assistant capable of generating lecture summaries, flashcards, and quizzes.',
      'Configured a backend document processor using libreoffice-convert to transform DOCX/PPTX slides into PDFs for frontend rendering.',
      'Implemented multi-format PDF rendering using React PDF and PDF.js to support interactive whiteboard and text highlighting features.',
      'Integrated Cloudinary for persistent media assets and Firebase SDK for secure file hosting and user authentication.',
      'Built responsive student and teacher dashboard layouts featuring smooth micro-animations using React, Tailwind CSS v4, and Framer Motion.',
    ],
    images: [
      '/Projects/c-study/02_CSP.webp',
      '/Projects/c-study/01_CSP.webp',
      '/Projects/c-study/03_CSP.webp',
      '/Projects/c-study/04_CSP.webp',
      '/Projects/c-study/06_CSP.webp',
    ],
    hoverImage: '/Projects/c-study/02_CSP.webp',
    github: 'https://github.com/aitezazdev/collaborative-study-platform',
    liveUrl: '',
  },
  {
    id: 2,
    slug: 'hms',
    title: 'Hospital Management System',
    year: '2025',
    tech: ['React', 'Express', 'Node.js', 'MongoDB', 'Google Gemini AI', 'Redux Toolkit', 'Tailwind CSS'],
    description:
      'A full stack hospital management system featuring dedicated, role based dashboards for patients, doctors, and system administrators. The platform integrates Google Gemini AI to assist both patients and medical staff through an interactive symptom checker, automated pre appointment medical history summaries, and suggested prescription generators. Patients can find doctors by specialization, book consultation slots, and track booking statuses, while doctors can manage schedules, record clinical notes, and edit prescriptions. Administrators oversee doctor registrations, verify credentials, and manage patient records with a global search interface.',
    myRole: [
      'Built the full-stack healthcare workflow using React, Express, Node.js, and MongoDB, incorporating Redux Toolkit for state management.',
      'Integrated Google Gemini API to implement a patient symptom advisor, pre-consultation medical history synthesis, and AI suggested prescriptions.',
      'Developed independent portals for patients, doctors, and admins with custom dashboards and schedule slot managers.',
      'Implemented doctor registration verification and appointment approval workflows.',
      'Created global patient and staff search functionality for administrative record management.',
      'Designed a fully responsive UI utilizing Tailwind CSS, Ant Design layouts, and custom loading states for AI text generation.',
    ],
    images: [
      '/Projects/HMS/hospital-1.webp',
      '/Projects/HMS/hospital-2.webp',
      '/Projects/HMS/hospital-3.webp',
      '/Projects/HMS/hospital-4.webp',
      '/Projects/HMS/hospital-5.webp',
      '/Projects/HMS/hospital-6.webp',
      '/Projects/HMS/hospital-7.webp',
      '/Projects/HMS/hospital-8.webp',
    ],
    hoverImage: '/Projects/HMS/hospital-1.webp',
    github: 'https://github.com/aitezazdev/Hospital-Mangment-System',
    liveUrl: 'https://aitezazdev-medicore.vercel.app/',
  },
  {
    id: 3,
    slug: 'ecommerce',
    title: 'Ecommerce-Next.js',
    year: '2026',
    tech: ['Next.js 16', 'React 19', 'TypeScript', 'Redux Toolkit', 'Stripe', 'MongoDB', 'Tailwind CSS'],
    description:
      'A high performance e-commerce platform built using the Next.js App Router and React 19 to provide a smooth, dark themed shopping experience. The storefront integrates server side rendering for catalog queries, category filters, and sorting parameters, allowing for fast initial loads and search optimization. A key feature is the database persisted shopping cart which uses React 19 transition states and optimistic updates to reflect quantity changes instantly, automatically rolling back to the cached Redux store if backend updates fail. Transactions are completed through a secure Stripe checkout session that collects delivery details, logs orders, and flushes cart states upon redirect confirmation. The backend includes database safeguards such as connection caching, a failure cooldown guard, and an offline mock dataset fallback to maintain stability.',
    myRole: [
      'Architected the full-stack catalog using Next.js App Router, TypeScript, and MongoDB, employing server-side data fetching for category collections.',
      'Integrated React 19 optimistic updates and transition hooks inside a custom React Context provider to enable zero-latency cart modifications.',
      'Engineered an end-to-end checkout pipeline with Stripe Checkout Sessions, capturing payment events, user details, and order logging.',
      'Configured a resilient Mongoose database connection wrapper featuring caching, a 10-second failure cooldown lock, and mock data fallbacks.',
      'Implemented type-safe form validation using Zod and React Hook Form on the frontend and custom validation middleware on API routes.',
      'Designed a responsive, dark-themed user interface utilizing Tailwind CSS, custom loading spinners, and skeleton loaders to minimize layout shifts.',
    ],
    images: [
      '/Projects/ecommerce/ecommerce-1.webp',
      '/Projects/ecommerce/ecommerce-2.webp',
      '/Projects/ecommerce/ecommerce-3.webp',
      '/Projects/ecommerce/ecommerce-4.webp',
      '/Projects/ecommerce/ecommerce-5.webp',
      '/Projects/ecommerce/ecommerce-6.webp',
    ],
    hoverImage: '/Projects/ecommerce/ecommerce-1.webp',
    github: 'https://github.com/aitezazdev/Next.js-Ecommerce',
    liveUrl: 'https://aitezazdev-ecommerce.vercel.app/',
  },
  {
    id: 4,
    slug: 'finance',
    title: 'Finance Tracker',
    year: '2025',
    tech: ['React', 'Express', 'Node.js', 'MongoDB', 'JWT Auth', 'Recharts.js', 'Tailwind CSS'],
    description:
      'A personal finance tracking application designed to help users log, organize, and review their daily incomes and expenses. The platform features an analytics dashboard that converts raw transaction feeds into interactive charts, including monthly spending comparisons, category breakdowns, and daily financial trends. Built with security in mind, the application secures all user records through JSON Web Tokens and bcrypt encryption. A global state store synchronizes transaction histories and user login states across the interface, utilizing request interceptors to automatically verify access tokens on outgoing API calls.',
    myRole: [
      'Developed the full stack application using the MERN stack and configured Redux Toolkit to manage global application states.',
      'Created interactive analytics dashboards using Recharts to visualize monthly income and expense metrics, category distributions, and spending trends.',
      'Implemented secure user authentication and authorization using JSON Web Tokens and bcrypt password hashing.',
      'Built transaction CRUD endpoints supporting dynamic category filtering and sorting by transaction amounts.',
      'Configured Axios interceptors to automatically append JWT bearer tokens to requests and handle session timeouts on 401 response codes.',
      'Designed a responsive client interface using Tailwind CSS, implementing alert notifications and table views for transaction management.',
    ],
    images: [
      '/Projects/financeTracker/finance-tracker-1.webp',
      '/Projects/financeTracker/finance-tracker-2.webp',
      '/Projects/financeTracker/finance-tracker-3.webp',
      '/Projects/financeTracker/finance-tracker-4.webp',
      '/Projects/financeTracker/finance-tracker-5.webp',
    ],
    hoverImage: '/Projects/financeTracker/finance-tracker-1.webp',
    github: 'https://github.com/aitezazdev/Finance-Tracker-Mern',
    liveUrl: 'https://aitezazdev-finance-tracker.vercel.app/',
  },
  {
    id: 5,
    slug: 'blog',
    title: 'Blog App',
    year: '2025',
    tech: ['React', 'Express', 'Node.js', 'MongoDB', 'JWT Auth', 'Cloudinary', 'Tailwind CSS'],
    description:
      'A full stack blogging application featuring a modern, responsive design and robust account management. The system implements secure JWT authentication, password encryption, and dynamic image uploads using Cloudinary. Users can publish articles, categorize posts with tags, interact through comments, save bookmarked reading lists, and manage their author profiles. Designed with performance in mind, the platform integrates MongoDB database indexes and an optimized connection cache to deliver fast, scalable query resolutions.',
    myRole: [
      'Architected the full stack system using React, Express, Node.js, and MongoDB, enforcing a clean modular codebase.',
      'Integrated Cloudinary and Multer disk storage to support dynamic image uploads, incorporating automated asset destruction routines during post updates and deletions.',
      'Engineered complex Mongoose database schemas featuring text indexing on key query fields and compound indexes to speed up chronological lookups.',
      'Developed a stateless, token-based authentication system utilizing JSON Web Tokens and bcrypt password hashing.',
      'Built a real-time search interface on the frontend with a debounced input handler to limit API request frequencies.',
      'Implemented a cascading database purge workflow that automatically removes posts, comments, likes, and Cloudinary media assets upon account deletion.',
      'Configured centralized state management using Redux Toolkit to persist user authentication states and bookmarks across page reloads.',
      'Created Axios request and response interceptors to handle automatic token attachment and graceful session expiration redirects.',
    ],
    images: [
      '/Projects/blogsite/blog-site.webp',
      '/Projects/blogsite/blog-site-2.webp',
      '/Projects/blogsite/blog-site-3.webp',
      '/Projects/blogsite/blog-site-4.webp',
    ],
    hoverImage: '/Projects/blogsite/blog-site.webp',
    github: 'https://github.com/aitezazdev/Blog-App-Mern',
    liveUrl: 'https://aitezazdev-blog-app.vercel.app/',
  },
];
export function getAllProjects() {
  return projects;
}
export function getProjectBySlug(slug) {
  return projects.find((p) => p.slug === slug);
}
